// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\Delays_1_block.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Delays_1_block
// Source Path: untitled/Pattern Recognition Neural Network/Layer 2/Delays 1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Delays_1_block
          (
           p_2,
           pd_2_1
          );


  input   [63:0] p_2;  // double
  output  [63:0] pd_2_1;  // double




  // <S10>/mux
  assign pd_2_1 = p_2;

endmodule  // Delays_1_block

