// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\Delays_1.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Delays_1
// Source Path: untitled/Pattern Recognition Neural Network/Layer 1/Delays 1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Delays_1
          (
           p_1_0,
           p_1_1,
           p_1_2,
           p_1_3,
           p_1_4,
           p_1_5,
           p_1_6,
           p_1_7,
           p_1_8,
           p_1_9,
           p_1_10,
           p_1_11,
           p_1_12,
           p_1_13,
           p_1_14,
           p_1_15,
           p_1_16,
           p_1_17,
           p_1_18,
           p_1_19,
           p_1_20,
           p_1_21,
           p_1_22,
           p_1_23,
           p_1_24,
           p_1_25,
           p_1_26,
           p_1_27,
           p_1_28,
           p_1_29,
           p_1_30,
           p_1_31,
           p_1_32,
           p_1_33,
           p_1_34,
           p_1_35,
           p_1_36,
           p_1_37,
           p_1_38,
           p_1_39,
           p_1_40,
           p_1_41,
           p_1_42,
           p_1_43,
           p_1_44,
           p_1_45,
           p_1_46,
           p_1_47,
           p_1_48,
           p_1_49,
           p_1_50,
           p_1_51,
           p_1_52,
           p_1_53,
           p_1_54,
           p_1_55,
           p_1_56,
           p_1_57,
           p_1_58,
           p_1_59,
           p_1_60,
           p_1_61,
           p_1_62,
           p_1_63,
           p_1_64,
           p_1_65,
           p_1_66,
           p_1_67,
           p_1_68,
           p_1_69,
           p_1_70,
           p_1_71,
           p_1_72,
           p_1_73,
           p_1_74,
           p_1_75,
           p_1_76,
           p_1_77,
           p_1_78,
           p_1_79,
           p_1_80,
           p_1_81,
           p_1_82,
           p_1_83,
           p_1_84,
           p_1_85,
           p_1_86,
           p_1_87,
           p_1_88,
           p_1_89,
           p_1_90,
           p_1_91,
           p_1_92,
           pd_1_1_0,
           pd_1_1_1,
           pd_1_1_2,
           pd_1_1_3,
           pd_1_1_4,
           pd_1_1_5,
           pd_1_1_6,
           pd_1_1_7,
           pd_1_1_8,
           pd_1_1_9,
           pd_1_1_10,
           pd_1_1_11,
           pd_1_1_12,
           pd_1_1_13,
           pd_1_1_14,
           pd_1_1_15,
           pd_1_1_16,
           pd_1_1_17,
           pd_1_1_18,
           pd_1_1_19,
           pd_1_1_20,
           pd_1_1_21,
           pd_1_1_22,
           pd_1_1_23,
           pd_1_1_24,
           pd_1_1_25,
           pd_1_1_26,
           pd_1_1_27,
           pd_1_1_28,
           pd_1_1_29,
           pd_1_1_30,
           pd_1_1_31,
           pd_1_1_32,
           pd_1_1_33,
           pd_1_1_34,
           pd_1_1_35,
           pd_1_1_36,
           pd_1_1_37,
           pd_1_1_38,
           pd_1_1_39,
           pd_1_1_40,
           pd_1_1_41,
           pd_1_1_42,
           pd_1_1_43,
           pd_1_1_44,
           pd_1_1_45,
           pd_1_1_46,
           pd_1_1_47,
           pd_1_1_48,
           pd_1_1_49,
           pd_1_1_50,
           pd_1_1_51,
           pd_1_1_52,
           pd_1_1_53,
           pd_1_1_54,
           pd_1_1_55,
           pd_1_1_56,
           pd_1_1_57,
           pd_1_1_58,
           pd_1_1_59,
           pd_1_1_60,
           pd_1_1_61,
           pd_1_1_62,
           pd_1_1_63,
           pd_1_1_64,
           pd_1_1_65,
           pd_1_1_66,
           pd_1_1_67,
           pd_1_1_68,
           pd_1_1_69,
           pd_1_1_70,
           pd_1_1_71,
           pd_1_1_72,
           pd_1_1_73,
           pd_1_1_74,
           pd_1_1_75,
           pd_1_1_76,
           pd_1_1_77,
           pd_1_1_78,
           pd_1_1_79,
           pd_1_1_80,
           pd_1_1_81,
           pd_1_1_82,
           pd_1_1_83,
           pd_1_1_84,
           pd_1_1_85,
           pd_1_1_86,
           pd_1_1_87,
           pd_1_1_88,
           pd_1_1_89,
           pd_1_1_90,
           pd_1_1_91,
           pd_1_1_92
          );


  input   [63:0] p_1_0;  // double
  input   [63:0] p_1_1;  // double
  input   [63:0] p_1_2;  // double
  input   [63:0] p_1_3;  // double
  input   [63:0] p_1_4;  // double
  input   [63:0] p_1_5;  // double
  input   [63:0] p_1_6;  // double
  input   [63:0] p_1_7;  // double
  input   [63:0] p_1_8;  // double
  input   [63:0] p_1_9;  // double
  input   [63:0] p_1_10;  // double
  input   [63:0] p_1_11;  // double
  input   [63:0] p_1_12;  // double
  input   [63:0] p_1_13;  // double
  input   [63:0] p_1_14;  // double
  input   [63:0] p_1_15;  // double
  input   [63:0] p_1_16;  // double
  input   [63:0] p_1_17;  // double
  input   [63:0] p_1_18;  // double
  input   [63:0] p_1_19;  // double
  input   [63:0] p_1_20;  // double
  input   [63:0] p_1_21;  // double
  input   [63:0] p_1_22;  // double
  input   [63:0] p_1_23;  // double
  input   [63:0] p_1_24;  // double
  input   [63:0] p_1_25;  // double
  input   [63:0] p_1_26;  // double
  input   [63:0] p_1_27;  // double
  input   [63:0] p_1_28;  // double
  input   [63:0] p_1_29;  // double
  input   [63:0] p_1_30;  // double
  input   [63:0] p_1_31;  // double
  input   [63:0] p_1_32;  // double
  input   [63:0] p_1_33;  // double
  input   [63:0] p_1_34;  // double
  input   [63:0] p_1_35;  // double
  input   [63:0] p_1_36;  // double
  input   [63:0] p_1_37;  // double
  input   [63:0] p_1_38;  // double
  input   [63:0] p_1_39;  // double
  input   [63:0] p_1_40;  // double
  input   [63:0] p_1_41;  // double
  input   [63:0] p_1_42;  // double
  input   [63:0] p_1_43;  // double
  input   [63:0] p_1_44;  // double
  input   [63:0] p_1_45;  // double
  input   [63:0] p_1_46;  // double
  input   [63:0] p_1_47;  // double
  input   [63:0] p_1_48;  // double
  input   [63:0] p_1_49;  // double
  input   [63:0] p_1_50;  // double
  input   [63:0] p_1_51;  // double
  input   [63:0] p_1_52;  // double
  input   [63:0] p_1_53;  // double
  input   [63:0] p_1_54;  // double
  input   [63:0] p_1_55;  // double
  input   [63:0] p_1_56;  // double
  input   [63:0] p_1_57;  // double
  input   [63:0] p_1_58;  // double
  input   [63:0] p_1_59;  // double
  input   [63:0] p_1_60;  // double
  input   [63:0] p_1_61;  // double
  input   [63:0] p_1_62;  // double
  input   [63:0] p_1_63;  // double
  input   [63:0] p_1_64;  // double
  input   [63:0] p_1_65;  // double
  input   [63:0] p_1_66;  // double
  input   [63:0] p_1_67;  // double
  input   [63:0] p_1_68;  // double
  input   [63:0] p_1_69;  // double
  input   [63:0] p_1_70;  // double
  input   [63:0] p_1_71;  // double
  input   [63:0] p_1_72;  // double
  input   [63:0] p_1_73;  // double
  input   [63:0] p_1_74;  // double
  input   [63:0] p_1_75;  // double
  input   [63:0] p_1_76;  // double
  input   [63:0] p_1_77;  // double
  input   [63:0] p_1_78;  // double
  input   [63:0] p_1_79;  // double
  input   [63:0] p_1_80;  // double
  input   [63:0] p_1_81;  // double
  input   [63:0] p_1_82;  // double
  input   [63:0] p_1_83;  // double
  input   [63:0] p_1_84;  // double
  input   [63:0] p_1_85;  // double
  input   [63:0] p_1_86;  // double
  input   [63:0] p_1_87;  // double
  input   [63:0] p_1_88;  // double
  input   [63:0] p_1_89;  // double
  input   [63:0] p_1_90;  // double
  input   [63:0] p_1_91;  // double
  input   [63:0] p_1_92;  // double
  output  [63:0] pd_1_1_0;  // double
  output  [63:0] pd_1_1_1;  // double
  output  [63:0] pd_1_1_2;  // double
  output  [63:0] pd_1_1_3;  // double
  output  [63:0] pd_1_1_4;  // double
  output  [63:0] pd_1_1_5;  // double
  output  [63:0] pd_1_1_6;  // double
  output  [63:0] pd_1_1_7;  // double
  output  [63:0] pd_1_1_8;  // double
  output  [63:0] pd_1_1_9;  // double
  output  [63:0] pd_1_1_10;  // double
  output  [63:0] pd_1_1_11;  // double
  output  [63:0] pd_1_1_12;  // double
  output  [63:0] pd_1_1_13;  // double
  output  [63:0] pd_1_1_14;  // double
  output  [63:0] pd_1_1_15;  // double
  output  [63:0] pd_1_1_16;  // double
  output  [63:0] pd_1_1_17;  // double
  output  [63:0] pd_1_1_18;  // double
  output  [63:0] pd_1_1_19;  // double
  output  [63:0] pd_1_1_20;  // double
  output  [63:0] pd_1_1_21;  // double
  output  [63:0] pd_1_1_22;  // double
  output  [63:0] pd_1_1_23;  // double
  output  [63:0] pd_1_1_24;  // double
  output  [63:0] pd_1_1_25;  // double
  output  [63:0] pd_1_1_26;  // double
  output  [63:0] pd_1_1_27;  // double
  output  [63:0] pd_1_1_28;  // double
  output  [63:0] pd_1_1_29;  // double
  output  [63:0] pd_1_1_30;  // double
  output  [63:0] pd_1_1_31;  // double
  output  [63:0] pd_1_1_32;  // double
  output  [63:0] pd_1_1_33;  // double
  output  [63:0] pd_1_1_34;  // double
  output  [63:0] pd_1_1_35;  // double
  output  [63:0] pd_1_1_36;  // double
  output  [63:0] pd_1_1_37;  // double
  output  [63:0] pd_1_1_38;  // double
  output  [63:0] pd_1_1_39;  // double
  output  [63:0] pd_1_1_40;  // double
  output  [63:0] pd_1_1_41;  // double
  output  [63:0] pd_1_1_42;  // double
  output  [63:0] pd_1_1_43;  // double
  output  [63:0] pd_1_1_44;  // double
  output  [63:0] pd_1_1_45;  // double
  output  [63:0] pd_1_1_46;  // double
  output  [63:0] pd_1_1_47;  // double
  output  [63:0] pd_1_1_48;  // double
  output  [63:0] pd_1_1_49;  // double
  output  [63:0] pd_1_1_50;  // double
  output  [63:0] pd_1_1_51;  // double
  output  [63:0] pd_1_1_52;  // double
  output  [63:0] pd_1_1_53;  // double
  output  [63:0] pd_1_1_54;  // double
  output  [63:0] pd_1_1_55;  // double
  output  [63:0] pd_1_1_56;  // double
  output  [63:0] pd_1_1_57;  // double
  output  [63:0] pd_1_1_58;  // double
  output  [63:0] pd_1_1_59;  // double
  output  [63:0] pd_1_1_60;  // double
  output  [63:0] pd_1_1_61;  // double
  output  [63:0] pd_1_1_62;  // double
  output  [63:0] pd_1_1_63;  // double
  output  [63:0] pd_1_1_64;  // double
  output  [63:0] pd_1_1_65;  // double
  output  [63:0] pd_1_1_66;  // double
  output  [63:0] pd_1_1_67;  // double
  output  [63:0] pd_1_1_68;  // double
  output  [63:0] pd_1_1_69;  // double
  output  [63:0] pd_1_1_70;  // double
  output  [63:0] pd_1_1_71;  // double
  output  [63:0] pd_1_1_72;  // double
  output  [63:0] pd_1_1_73;  // double
  output  [63:0] pd_1_1_74;  // double
  output  [63:0] pd_1_1_75;  // double
  output  [63:0] pd_1_1_76;  // double
  output  [63:0] pd_1_1_77;  // double
  output  [63:0] pd_1_1_78;  // double
  output  [63:0] pd_1_1_79;  // double
  output  [63:0] pd_1_1_80;  // double
  output  [63:0] pd_1_1_81;  // double
  output  [63:0] pd_1_1_82;  // double
  output  [63:0] pd_1_1_83;  // double
  output  [63:0] pd_1_1_84;  // double
  output  [63:0] pd_1_1_85;  // double
  output  [63:0] pd_1_1_86;  // double
  output  [63:0] pd_1_1_87;  // double
  output  [63:0] pd_1_1_88;  // double
  output  [63:0] pd_1_1_89;  // double
  output  [63:0] pd_1_1_90;  // double
  output  [63:0] pd_1_1_91;  // double
  output  [63:0] pd_1_1_92;  // double




  assign pd_1_1_0 = p_1_0;

  assign pd_1_1_1 = p_1_1;

  assign pd_1_1_2 = p_1_2;

  assign pd_1_1_3 = p_1_3;

  assign pd_1_1_4 = p_1_4;

  assign pd_1_1_5 = p_1_5;

  assign pd_1_1_6 = p_1_6;

  assign pd_1_1_7 = p_1_7;

  assign pd_1_1_8 = p_1_8;

  assign pd_1_1_9 = p_1_9;

  assign pd_1_1_10 = p_1_10;

  assign pd_1_1_11 = p_1_11;

  assign pd_1_1_12 = p_1_12;

  assign pd_1_1_13 = p_1_13;

  assign pd_1_1_14 = p_1_14;

  assign pd_1_1_15 = p_1_15;

  assign pd_1_1_16 = p_1_16;

  assign pd_1_1_17 = p_1_17;

  assign pd_1_1_18 = p_1_18;

  assign pd_1_1_19 = p_1_19;

  assign pd_1_1_20 = p_1_20;

  assign pd_1_1_21 = p_1_21;

  assign pd_1_1_22 = p_1_22;

  assign pd_1_1_23 = p_1_23;

  assign pd_1_1_24 = p_1_24;

  assign pd_1_1_25 = p_1_25;

  assign pd_1_1_26 = p_1_26;

  assign pd_1_1_27 = p_1_27;

  assign pd_1_1_28 = p_1_28;

  assign pd_1_1_29 = p_1_29;

  assign pd_1_1_30 = p_1_30;

  assign pd_1_1_31 = p_1_31;

  assign pd_1_1_32 = p_1_32;

  assign pd_1_1_33 = p_1_33;

  assign pd_1_1_34 = p_1_34;

  assign pd_1_1_35 = p_1_35;

  assign pd_1_1_36 = p_1_36;

  assign pd_1_1_37 = p_1_37;

  assign pd_1_1_38 = p_1_38;

  assign pd_1_1_39 = p_1_39;

  assign pd_1_1_40 = p_1_40;

  assign pd_1_1_41 = p_1_41;

  assign pd_1_1_42 = p_1_42;

  assign pd_1_1_43 = p_1_43;

  assign pd_1_1_44 = p_1_44;

  assign pd_1_1_45 = p_1_45;

  assign pd_1_1_46 = p_1_46;

  assign pd_1_1_47 = p_1_47;

  assign pd_1_1_48 = p_1_48;

  assign pd_1_1_49 = p_1_49;

  assign pd_1_1_50 = p_1_50;

  assign pd_1_1_51 = p_1_51;

  assign pd_1_1_52 = p_1_52;

  assign pd_1_1_53 = p_1_53;

  assign pd_1_1_54 = p_1_54;

  assign pd_1_1_55 = p_1_55;

  assign pd_1_1_56 = p_1_56;

  assign pd_1_1_57 = p_1_57;

  assign pd_1_1_58 = p_1_58;

  assign pd_1_1_59 = p_1_59;

  assign pd_1_1_60 = p_1_60;

  assign pd_1_1_61 = p_1_61;

  assign pd_1_1_62 = p_1_62;

  assign pd_1_1_63 = p_1_63;

  assign pd_1_1_64 = p_1_64;

  assign pd_1_1_65 = p_1_65;

  assign pd_1_1_66 = p_1_66;

  assign pd_1_1_67 = p_1_67;

  assign pd_1_1_68 = p_1_68;

  assign pd_1_1_69 = p_1_69;

  assign pd_1_1_70 = p_1_70;

  assign pd_1_1_71 = p_1_71;

  assign pd_1_1_72 = p_1_72;

  assign pd_1_1_73 = p_1_73;

  assign pd_1_1_74 = p_1_74;

  assign pd_1_1_75 = p_1_75;

  assign pd_1_1_76 = p_1_76;

  assign pd_1_1_77 = p_1_77;

  assign pd_1_1_78 = p_1_78;

  assign pd_1_1_79 = p_1_79;

  assign pd_1_1_80 = p_1_80;

  assign pd_1_1_81 = p_1_81;

  assign pd_1_1_82 = p_1_82;

  assign pd_1_1_83 = p_1_83;

  assign pd_1_1_84 = p_1_84;

  assign pd_1_1_85 = p_1_85;

  assign pd_1_1_86 = p_1_86;

  assign pd_1_1_87 = p_1_87;

  assign pd_1_1_88 = p_1_88;

  assign pd_1_1_89 = p_1_89;

  assign pd_1_1_90 = p_1_90;

  assign pd_1_1_91 = p_1_91;

  assign pd_1_1_92 = p_1_92;

endmodule  // Delays_1

