// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\Layer_1.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Layer_1
// Source Path: untitled/Pattern Recognition Neural Network/Layer 1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Layer_1
          (
           p_1_0,
           p_1_1,
           p_1_2,
           p_1_3,
           p_1_4,
           p_1_5,
           p_1_6,
           p_1_7,
           p_1_8,
           p_1_9,
           p_1_10,
           p_1_11,
           p_1_12,
           p_1_13,
           p_1_14,
           p_1_15,
           p_1_16,
           p_1_17,
           p_1_18,
           p_1_19,
           p_1_20,
           p_1_21,
           p_1_22,
           p_1_23,
           p_1_24,
           p_1_25,
           p_1_26,
           p_1_27,
           p_1_28,
           p_1_29,
           p_1_30,
           p_1_31,
           p_1_32,
           p_1_33,
           p_1_34,
           p_1_35,
           p_1_36,
           p_1_37,
           p_1_38,
           p_1_39,
           p_1_40,
           p_1_41,
           p_1_42,
           p_1_43,
           p_1_44,
           p_1_45,
           p_1_46,
           p_1_47,
           p_1_48,
           p_1_49,
           p_1_50,
           p_1_51,
           p_1_52,
           p_1_53,
           p_1_54,
           p_1_55,
           p_1_56,
           p_1_57,
           p_1_58,
           p_1_59,
           p_1_60,
           p_1_61,
           p_1_62,
           p_1_63,
           p_1_64,
           p_1_65,
           p_1_66,
           p_1_67,
           p_1_68,
           p_1_69,
           p_1_70,
           p_1_71,
           p_1_72,
           p_1_73,
           p_1_74,
           p_1_75,
           p_1_76,
           p_1_77,
           p_1_78,
           p_1_79,
           p_1_80,
           p_1_81,
           p_1_82,
           p_1_83,
           p_1_84,
           p_1_85,
           p_1_86,
           p_1_87,
           p_1_88,
           p_1_89,
           p_1_90,
           p_1_91,
           p_1_92,
           a_1
          );


  input   [63:0] p_1_0;  // double
  input   [63:0] p_1_1;  // double
  input   [63:0] p_1_2;  // double
  input   [63:0] p_1_3;  // double
  input   [63:0] p_1_4;  // double
  input   [63:0] p_1_5;  // double
  input   [63:0] p_1_6;  // double
  input   [63:0] p_1_7;  // double
  input   [63:0] p_1_8;  // double
  input   [63:0] p_1_9;  // double
  input   [63:0] p_1_10;  // double
  input   [63:0] p_1_11;  // double
  input   [63:0] p_1_12;  // double
  input   [63:0] p_1_13;  // double
  input   [63:0] p_1_14;  // double
  input   [63:0] p_1_15;  // double
  input   [63:0] p_1_16;  // double
  input   [63:0] p_1_17;  // double
  input   [63:0] p_1_18;  // double
  input   [63:0] p_1_19;  // double
  input   [63:0] p_1_20;  // double
  input   [63:0] p_1_21;  // double
  input   [63:0] p_1_22;  // double
  input   [63:0] p_1_23;  // double
  input   [63:0] p_1_24;  // double
  input   [63:0] p_1_25;  // double
  input   [63:0] p_1_26;  // double
  input   [63:0] p_1_27;  // double
  input   [63:0] p_1_28;  // double
  input   [63:0] p_1_29;  // double
  input   [63:0] p_1_30;  // double
  input   [63:0] p_1_31;  // double
  input   [63:0] p_1_32;  // double
  input   [63:0] p_1_33;  // double
  input   [63:0] p_1_34;  // double
  input   [63:0] p_1_35;  // double
  input   [63:0] p_1_36;  // double
  input   [63:0] p_1_37;  // double
  input   [63:0] p_1_38;  // double
  input   [63:0] p_1_39;  // double
  input   [63:0] p_1_40;  // double
  input   [63:0] p_1_41;  // double
  input   [63:0] p_1_42;  // double
  input   [63:0] p_1_43;  // double
  input   [63:0] p_1_44;  // double
  input   [63:0] p_1_45;  // double
  input   [63:0] p_1_46;  // double
  input   [63:0] p_1_47;  // double
  input   [63:0] p_1_48;  // double
  input   [63:0] p_1_49;  // double
  input   [63:0] p_1_50;  // double
  input   [63:0] p_1_51;  // double
  input   [63:0] p_1_52;  // double
  input   [63:0] p_1_53;  // double
  input   [63:0] p_1_54;  // double
  input   [63:0] p_1_55;  // double
  input   [63:0] p_1_56;  // double
  input   [63:0] p_1_57;  // double
  input   [63:0] p_1_58;  // double
  input   [63:0] p_1_59;  // double
  input   [63:0] p_1_60;  // double
  input   [63:0] p_1_61;  // double
  input   [63:0] p_1_62;  // double
  input   [63:0] p_1_63;  // double
  input   [63:0] p_1_64;  // double
  input   [63:0] p_1_65;  // double
  input   [63:0] p_1_66;  // double
  input   [63:0] p_1_67;  // double
  input   [63:0] p_1_68;  // double
  input   [63:0] p_1_69;  // double
  input   [63:0] p_1_70;  // double
  input   [63:0] p_1_71;  // double
  input   [63:0] p_1_72;  // double
  input   [63:0] p_1_73;  // double
  input   [63:0] p_1_74;  // double
  input   [63:0] p_1_75;  // double
  input   [63:0] p_1_76;  // double
  input   [63:0] p_1_77;  // double
  input   [63:0] p_1_78;  // double
  input   [63:0] p_1_79;  // double
  input   [63:0] p_1_80;  // double
  input   [63:0] p_1_81;  // double
  input   [63:0] p_1_82;  // double
  input   [63:0] p_1_83;  // double
  input   [63:0] p_1_84;  // double
  input   [63:0] p_1_85;  // double
  input   [63:0] p_1_86;  // double
  input   [63:0] p_1_87;  // double
  input   [63:0] p_1_88;  // double
  input   [63:0] p_1_89;  // double
  input   [63:0] p_1_90;  // double
  input   [63:0] p_1_91;  // double
  input   [63:0] p_1_92;  // double
  output  [63:0] a_1;  // double


  wire [63:0] Delays_1_out1_0;  // ufix64
  wire [63:0] Delays_1_out1_1;  // ufix64
  wire [63:0] Delays_1_out1_2;  // ufix64
  wire [63:0] Delays_1_out1_3;  // ufix64
  wire [63:0] Delays_1_out1_4;  // ufix64
  wire [63:0] Delays_1_out1_5;  // ufix64
  wire [63:0] Delays_1_out1_6;  // ufix64
  wire [63:0] Delays_1_out1_7;  // ufix64
  wire [63:0] Delays_1_out1_8;  // ufix64
  wire [63:0] Delays_1_out1_9;  // ufix64
  wire [63:0] Delays_1_out1_10;  // ufix64
  wire [63:0] Delays_1_out1_11;  // ufix64
  wire [63:0] Delays_1_out1_12;  // ufix64
  wire [63:0] Delays_1_out1_13;  // ufix64
  wire [63:0] Delays_1_out1_14;  // ufix64
  wire [63:0] Delays_1_out1_15;  // ufix64
  wire [63:0] Delays_1_out1_16;  // ufix64
  wire [63:0] Delays_1_out1_17;  // ufix64
  wire [63:0] Delays_1_out1_18;  // ufix64
  wire [63:0] Delays_1_out1_19;  // ufix64
  wire [63:0] Delays_1_out1_20;  // ufix64
  wire [63:0] Delays_1_out1_21;  // ufix64
  wire [63:0] Delays_1_out1_22;  // ufix64
  wire [63:0] Delays_1_out1_23;  // ufix64
  wire [63:0] Delays_1_out1_24;  // ufix64
  wire [63:0] Delays_1_out1_25;  // ufix64
  wire [63:0] Delays_1_out1_26;  // ufix64
  wire [63:0] Delays_1_out1_27;  // ufix64
  wire [63:0] Delays_1_out1_28;  // ufix64
  wire [63:0] Delays_1_out1_29;  // ufix64
  wire [63:0] Delays_1_out1_30;  // ufix64
  wire [63:0] Delays_1_out1_31;  // ufix64
  wire [63:0] Delays_1_out1_32;  // ufix64
  wire [63:0] Delays_1_out1_33;  // ufix64
  wire [63:0] Delays_1_out1_34;  // ufix64
  wire [63:0] Delays_1_out1_35;  // ufix64
  wire [63:0] Delays_1_out1_36;  // ufix64
  wire [63:0] Delays_1_out1_37;  // ufix64
  wire [63:0] Delays_1_out1_38;  // ufix64
  wire [63:0] Delays_1_out1_39;  // ufix64
  wire [63:0] Delays_1_out1_40;  // ufix64
  wire [63:0] Delays_1_out1_41;  // ufix64
  wire [63:0] Delays_1_out1_42;  // ufix64
  wire [63:0] Delays_1_out1_43;  // ufix64
  wire [63:0] Delays_1_out1_44;  // ufix64
  wire [63:0] Delays_1_out1_45;  // ufix64
  wire [63:0] Delays_1_out1_46;  // ufix64
  wire [63:0] Delays_1_out1_47;  // ufix64
  wire [63:0] Delays_1_out1_48;  // ufix64
  wire [63:0] Delays_1_out1_49;  // ufix64
  wire [63:0] Delays_1_out1_50;  // ufix64
  wire [63:0] Delays_1_out1_51;  // ufix64
  wire [63:0] Delays_1_out1_52;  // ufix64
  wire [63:0] Delays_1_out1_53;  // ufix64
  wire [63:0] Delays_1_out1_54;  // ufix64
  wire [63:0] Delays_1_out1_55;  // ufix64
  wire [63:0] Delays_1_out1_56;  // ufix64
  wire [63:0] Delays_1_out1_57;  // ufix64
  wire [63:0] Delays_1_out1_58;  // ufix64
  wire [63:0] Delays_1_out1_59;  // ufix64
  wire [63:0] Delays_1_out1_60;  // ufix64
  wire [63:0] Delays_1_out1_61;  // ufix64
  wire [63:0] Delays_1_out1_62;  // ufix64
  wire [63:0] Delays_1_out1_63;  // ufix64
  wire [63:0] Delays_1_out1_64;  // ufix64
  wire [63:0] Delays_1_out1_65;  // ufix64
  wire [63:0] Delays_1_out1_66;  // ufix64
  wire [63:0] Delays_1_out1_67;  // ufix64
  wire [63:0] Delays_1_out1_68;  // ufix64
  wire [63:0] Delays_1_out1_69;  // ufix64
  wire [63:0] Delays_1_out1_70;  // ufix64
  wire [63:0] Delays_1_out1_71;  // ufix64
  wire [63:0] Delays_1_out1_72;  // ufix64
  wire [63:0] Delays_1_out1_73;  // ufix64
  wire [63:0] Delays_1_out1_74;  // ufix64
  wire [63:0] Delays_1_out1_75;  // ufix64
  wire [63:0] Delays_1_out1_76;  // ufix64
  wire [63:0] Delays_1_out1_77;  // ufix64
  wire [63:0] Delays_1_out1_78;  // ufix64
  wire [63:0] Delays_1_out1_79;  // ufix64
  wire [63:0] Delays_1_out1_80;  // ufix64
  wire [63:0] Delays_1_out1_81;  // ufix64
  wire [63:0] Delays_1_out1_82;  // ufix64
  wire [63:0] Delays_1_out1_83;  // ufix64
  wire [63:0] Delays_1_out1_84;  // ufix64
  wire [63:0] Delays_1_out1_85;  // ufix64
  wire [63:0] Delays_1_out1_86;  // ufix64
  wire [63:0] Delays_1_out1_87;  // ufix64
  wire [63:0] Delays_1_out1_88;  // ufix64
  wire [63:0] Delays_1_out1_89;  // ufix64
  wire [63:0] Delays_1_out1_90;  // ufix64
  wire [63:0] Delays_1_out1_91;  // ufix64
  wire [63:0] Delays_1_out1_92;  // ufix64
  wire [63:0] IW_1_1_out1;  // ufix64
  real IW_1_1_out1_double;  // double
  real b_1_out1;  // double
  real netsum_out1;  // double
  wire [63:0] poslin_out1;  // ufix64


  // <S2>/Delays 1
  Delays_1   u_Delays_1   (.p_1_0(p_1_0),  // double
                           .p_1_1(p_1_1),  // double
                           .p_1_2(p_1_2),  // double
                           .p_1_3(p_1_3),  // double
                           .p_1_4(p_1_4),  // double
                           .p_1_5(p_1_5),  // double
                           .p_1_6(p_1_6),  // double
                           .p_1_7(p_1_7),  // double
                           .p_1_8(p_1_8),  // double
                           .p_1_9(p_1_9),  // double
                           .p_1_10(p_1_10),  // double
                           .p_1_11(p_1_11),  // double
                           .p_1_12(p_1_12),  // double
                           .p_1_13(p_1_13),  // double
                           .p_1_14(p_1_14),  // double
                           .p_1_15(p_1_15),  // double
                           .p_1_16(p_1_16),  // double
                           .p_1_17(p_1_17),  // double
                           .p_1_18(p_1_18),  // double
                           .p_1_19(p_1_19),  // double
                           .p_1_20(p_1_20),  // double
                           .p_1_21(p_1_21),  // double
                           .p_1_22(p_1_22),  // double
                           .p_1_23(p_1_23),  // double
                           .p_1_24(p_1_24),  // double
                           .p_1_25(p_1_25),  // double
                           .p_1_26(p_1_26),  // double
                           .p_1_27(p_1_27),  // double
                           .p_1_28(p_1_28),  // double
                           .p_1_29(p_1_29),  // double
                           .p_1_30(p_1_30),  // double
                           .p_1_31(p_1_31),  // double
                           .p_1_32(p_1_32),  // double
                           .p_1_33(p_1_33),  // double
                           .p_1_34(p_1_34),  // double
                           .p_1_35(p_1_35),  // double
                           .p_1_36(p_1_36),  // double
                           .p_1_37(p_1_37),  // double
                           .p_1_38(p_1_38),  // double
                           .p_1_39(p_1_39),  // double
                           .p_1_40(p_1_40),  // double
                           .p_1_41(p_1_41),  // double
                           .p_1_42(p_1_42),  // double
                           .p_1_43(p_1_43),  // double
                           .p_1_44(p_1_44),  // double
                           .p_1_45(p_1_45),  // double
                           .p_1_46(p_1_46),  // double
                           .p_1_47(p_1_47),  // double
                           .p_1_48(p_1_48),  // double
                           .p_1_49(p_1_49),  // double
                           .p_1_50(p_1_50),  // double
                           .p_1_51(p_1_51),  // double
                           .p_1_52(p_1_52),  // double
                           .p_1_53(p_1_53),  // double
                           .p_1_54(p_1_54),  // double
                           .p_1_55(p_1_55),  // double
                           .p_1_56(p_1_56),  // double
                           .p_1_57(p_1_57),  // double
                           .p_1_58(p_1_58),  // double
                           .p_1_59(p_1_59),  // double
                           .p_1_60(p_1_60),  // double
                           .p_1_61(p_1_61),  // double
                           .p_1_62(p_1_62),  // double
                           .p_1_63(p_1_63),  // double
                           .p_1_64(p_1_64),  // double
                           .p_1_65(p_1_65),  // double
                           .p_1_66(p_1_66),  // double
                           .p_1_67(p_1_67),  // double
                           .p_1_68(p_1_68),  // double
                           .p_1_69(p_1_69),  // double
                           .p_1_70(p_1_70),  // double
                           .p_1_71(p_1_71),  // double
                           .p_1_72(p_1_72),  // double
                           .p_1_73(p_1_73),  // double
                           .p_1_74(p_1_74),  // double
                           .p_1_75(p_1_75),  // double
                           .p_1_76(p_1_76),  // double
                           .p_1_77(p_1_77),  // double
                           .p_1_78(p_1_78),  // double
                           .p_1_79(p_1_79),  // double
                           .p_1_80(p_1_80),  // double
                           .p_1_81(p_1_81),  // double
                           .p_1_82(p_1_82),  // double
                           .p_1_83(p_1_83),  // double
                           .p_1_84(p_1_84),  // double
                           .p_1_85(p_1_85),  // double
                           .p_1_86(p_1_86),  // double
                           .p_1_87(p_1_87),  // double
                           .p_1_88(p_1_88),  // double
                           .p_1_89(p_1_89),  // double
                           .p_1_90(p_1_90),  // double
                           .p_1_91(p_1_91),  // double
                           .p_1_92(p_1_92),  // double
                           .pd_1_1_0(Delays_1_out1_0),  // double
                           .pd_1_1_1(Delays_1_out1_1),  // double
                           .pd_1_1_2(Delays_1_out1_2),  // double
                           .pd_1_1_3(Delays_1_out1_3),  // double
                           .pd_1_1_4(Delays_1_out1_4),  // double
                           .pd_1_1_5(Delays_1_out1_5),  // double
                           .pd_1_1_6(Delays_1_out1_6),  // double
                           .pd_1_1_7(Delays_1_out1_7),  // double
                           .pd_1_1_8(Delays_1_out1_8),  // double
                           .pd_1_1_9(Delays_1_out1_9),  // double
                           .pd_1_1_10(Delays_1_out1_10),  // double
                           .pd_1_1_11(Delays_1_out1_11),  // double
                           .pd_1_1_12(Delays_1_out1_12),  // double
                           .pd_1_1_13(Delays_1_out1_13),  // double
                           .pd_1_1_14(Delays_1_out1_14),  // double
                           .pd_1_1_15(Delays_1_out1_15),  // double
                           .pd_1_1_16(Delays_1_out1_16),  // double
                           .pd_1_1_17(Delays_1_out1_17),  // double
                           .pd_1_1_18(Delays_1_out1_18),  // double
                           .pd_1_1_19(Delays_1_out1_19),  // double
                           .pd_1_1_20(Delays_1_out1_20),  // double
                           .pd_1_1_21(Delays_1_out1_21),  // double
                           .pd_1_1_22(Delays_1_out1_22),  // double
                           .pd_1_1_23(Delays_1_out1_23),  // double
                           .pd_1_1_24(Delays_1_out1_24),  // double
                           .pd_1_1_25(Delays_1_out1_25),  // double
                           .pd_1_1_26(Delays_1_out1_26),  // double
                           .pd_1_1_27(Delays_1_out1_27),  // double
                           .pd_1_1_28(Delays_1_out1_28),  // double
                           .pd_1_1_29(Delays_1_out1_29),  // double
                           .pd_1_1_30(Delays_1_out1_30),  // double
                           .pd_1_1_31(Delays_1_out1_31),  // double
                           .pd_1_1_32(Delays_1_out1_32),  // double
                           .pd_1_1_33(Delays_1_out1_33),  // double
                           .pd_1_1_34(Delays_1_out1_34),  // double
                           .pd_1_1_35(Delays_1_out1_35),  // double
                           .pd_1_1_36(Delays_1_out1_36),  // double
                           .pd_1_1_37(Delays_1_out1_37),  // double
                           .pd_1_1_38(Delays_1_out1_38),  // double
                           .pd_1_1_39(Delays_1_out1_39),  // double
                           .pd_1_1_40(Delays_1_out1_40),  // double
                           .pd_1_1_41(Delays_1_out1_41),  // double
                           .pd_1_1_42(Delays_1_out1_42),  // double
                           .pd_1_1_43(Delays_1_out1_43),  // double
                           .pd_1_1_44(Delays_1_out1_44),  // double
                           .pd_1_1_45(Delays_1_out1_45),  // double
                           .pd_1_1_46(Delays_1_out1_46),  // double
                           .pd_1_1_47(Delays_1_out1_47),  // double
                           .pd_1_1_48(Delays_1_out1_48),  // double
                           .pd_1_1_49(Delays_1_out1_49),  // double
                           .pd_1_1_50(Delays_1_out1_50),  // double
                           .pd_1_1_51(Delays_1_out1_51),  // double
                           .pd_1_1_52(Delays_1_out1_52),  // double
                           .pd_1_1_53(Delays_1_out1_53),  // double
                           .pd_1_1_54(Delays_1_out1_54),  // double
                           .pd_1_1_55(Delays_1_out1_55),  // double
                           .pd_1_1_56(Delays_1_out1_56),  // double
                           .pd_1_1_57(Delays_1_out1_57),  // double
                           .pd_1_1_58(Delays_1_out1_58),  // double
                           .pd_1_1_59(Delays_1_out1_59),  // double
                           .pd_1_1_60(Delays_1_out1_60),  // double
                           .pd_1_1_61(Delays_1_out1_61),  // double
                           .pd_1_1_62(Delays_1_out1_62),  // double
                           .pd_1_1_63(Delays_1_out1_63),  // double
                           .pd_1_1_64(Delays_1_out1_64),  // double
                           .pd_1_1_65(Delays_1_out1_65),  // double
                           .pd_1_1_66(Delays_1_out1_66),  // double
                           .pd_1_1_67(Delays_1_out1_67),  // double
                           .pd_1_1_68(Delays_1_out1_68),  // double
                           .pd_1_1_69(Delays_1_out1_69),  // double
                           .pd_1_1_70(Delays_1_out1_70),  // double
                           .pd_1_1_71(Delays_1_out1_71),  // double
                           .pd_1_1_72(Delays_1_out1_72),  // double
                           .pd_1_1_73(Delays_1_out1_73),  // double
                           .pd_1_1_74(Delays_1_out1_74),  // double
                           .pd_1_1_75(Delays_1_out1_75),  // double
                           .pd_1_1_76(Delays_1_out1_76),  // double
                           .pd_1_1_77(Delays_1_out1_77),  // double
                           .pd_1_1_78(Delays_1_out1_78),  // double
                           .pd_1_1_79(Delays_1_out1_79),  // double
                           .pd_1_1_80(Delays_1_out1_80),  // double
                           .pd_1_1_81(Delays_1_out1_81),  // double
                           .pd_1_1_82(Delays_1_out1_82),  // double
                           .pd_1_1_83(Delays_1_out1_83),  // double
                           .pd_1_1_84(Delays_1_out1_84),  // double
                           .pd_1_1_85(Delays_1_out1_85),  // double
                           .pd_1_1_86(Delays_1_out1_86),  // double
                           .pd_1_1_87(Delays_1_out1_87),  // double
                           .pd_1_1_88(Delays_1_out1_88),  // double
                           .pd_1_1_89(Delays_1_out1_89),  // double
                           .pd_1_1_90(Delays_1_out1_90),  // double
                           .pd_1_1_91(Delays_1_out1_91),  // double
                           .pd_1_1_92(Delays_1_out1_92)  // double
                           );

  // <S2>/IW{1,1}
  IW_1_1   u_IW_1_1   (.pd_1_1_0(Delays_1_out1_0),  // double
                       .pd_1_1_1(Delays_1_out1_1),  // double
                       .pd_1_1_2(Delays_1_out1_2),  // double
                       .pd_1_1_3(Delays_1_out1_3),  // double
                       .pd_1_1_4(Delays_1_out1_4),  // double
                       .pd_1_1_5(Delays_1_out1_5),  // double
                       .pd_1_1_6(Delays_1_out1_6),  // double
                       .pd_1_1_7(Delays_1_out1_7),  // double
                       .pd_1_1_8(Delays_1_out1_8),  // double
                       .pd_1_1_9(Delays_1_out1_9),  // double
                       .pd_1_1_10(Delays_1_out1_10),  // double
                       .pd_1_1_11(Delays_1_out1_11),  // double
                       .pd_1_1_12(Delays_1_out1_12),  // double
                       .pd_1_1_13(Delays_1_out1_13),  // double
                       .pd_1_1_14(Delays_1_out1_14),  // double
                       .pd_1_1_15(Delays_1_out1_15),  // double
                       .pd_1_1_16(Delays_1_out1_16),  // double
                       .pd_1_1_17(Delays_1_out1_17),  // double
                       .pd_1_1_18(Delays_1_out1_18),  // double
                       .pd_1_1_19(Delays_1_out1_19),  // double
                       .pd_1_1_20(Delays_1_out1_20),  // double
                       .pd_1_1_21(Delays_1_out1_21),  // double
                       .pd_1_1_22(Delays_1_out1_22),  // double
                       .pd_1_1_23(Delays_1_out1_23),  // double
                       .pd_1_1_24(Delays_1_out1_24),  // double
                       .pd_1_1_25(Delays_1_out1_25),  // double
                       .pd_1_1_26(Delays_1_out1_26),  // double
                       .pd_1_1_27(Delays_1_out1_27),  // double
                       .pd_1_1_28(Delays_1_out1_28),  // double
                       .pd_1_1_29(Delays_1_out1_29),  // double
                       .pd_1_1_30(Delays_1_out1_30),  // double
                       .pd_1_1_31(Delays_1_out1_31),  // double
                       .pd_1_1_32(Delays_1_out1_32),  // double
                       .pd_1_1_33(Delays_1_out1_33),  // double
                       .pd_1_1_34(Delays_1_out1_34),  // double
                       .pd_1_1_35(Delays_1_out1_35),  // double
                       .pd_1_1_36(Delays_1_out1_36),  // double
                       .pd_1_1_37(Delays_1_out1_37),  // double
                       .pd_1_1_38(Delays_1_out1_38),  // double
                       .pd_1_1_39(Delays_1_out1_39),  // double
                       .pd_1_1_40(Delays_1_out1_40),  // double
                       .pd_1_1_41(Delays_1_out1_41),  // double
                       .pd_1_1_42(Delays_1_out1_42),  // double
                       .pd_1_1_43(Delays_1_out1_43),  // double
                       .pd_1_1_44(Delays_1_out1_44),  // double
                       .pd_1_1_45(Delays_1_out1_45),  // double
                       .pd_1_1_46(Delays_1_out1_46),  // double
                       .pd_1_1_47(Delays_1_out1_47),  // double
                       .pd_1_1_48(Delays_1_out1_48),  // double
                       .pd_1_1_49(Delays_1_out1_49),  // double
                       .pd_1_1_50(Delays_1_out1_50),  // double
                       .pd_1_1_51(Delays_1_out1_51),  // double
                       .pd_1_1_52(Delays_1_out1_52),  // double
                       .pd_1_1_53(Delays_1_out1_53),  // double
                       .pd_1_1_54(Delays_1_out1_54),  // double
                       .pd_1_1_55(Delays_1_out1_55),  // double
                       .pd_1_1_56(Delays_1_out1_56),  // double
                       .pd_1_1_57(Delays_1_out1_57),  // double
                       .pd_1_1_58(Delays_1_out1_58),  // double
                       .pd_1_1_59(Delays_1_out1_59),  // double
                       .pd_1_1_60(Delays_1_out1_60),  // double
                       .pd_1_1_61(Delays_1_out1_61),  // double
                       .pd_1_1_62(Delays_1_out1_62),  // double
                       .pd_1_1_63(Delays_1_out1_63),  // double
                       .pd_1_1_64(Delays_1_out1_64),  // double
                       .pd_1_1_65(Delays_1_out1_65),  // double
                       .pd_1_1_66(Delays_1_out1_66),  // double
                       .pd_1_1_67(Delays_1_out1_67),  // double
                       .pd_1_1_68(Delays_1_out1_68),  // double
                       .pd_1_1_69(Delays_1_out1_69),  // double
                       .pd_1_1_70(Delays_1_out1_70),  // double
                       .pd_1_1_71(Delays_1_out1_71),  // double
                       .pd_1_1_72(Delays_1_out1_72),  // double
                       .pd_1_1_73(Delays_1_out1_73),  // double
                       .pd_1_1_74(Delays_1_out1_74),  // double
                       .pd_1_1_75(Delays_1_out1_75),  // double
                       .pd_1_1_76(Delays_1_out1_76),  // double
                       .pd_1_1_77(Delays_1_out1_77),  // double
                       .pd_1_1_78(Delays_1_out1_78),  // double
                       .pd_1_1_79(Delays_1_out1_79),  // double
                       .pd_1_1_80(Delays_1_out1_80),  // double
                       .pd_1_1_81(Delays_1_out1_81),  // double
                       .pd_1_1_82(Delays_1_out1_82),  // double
                       .pd_1_1_83(Delays_1_out1_83),  // double
                       .pd_1_1_84(Delays_1_out1_84),  // double
                       .pd_1_1_85(Delays_1_out1_85),  // double
                       .pd_1_1_86(Delays_1_out1_86),  // double
                       .pd_1_1_87(Delays_1_out1_87),  // double
                       .pd_1_1_88(Delays_1_out1_88),  // double
                       .pd_1_1_89(Delays_1_out1_89),  // double
                       .pd_1_1_90(Delays_1_out1_90),  // double
                       .pd_1_1_91(Delays_1_out1_91),  // double
                       .pd_1_1_92(Delays_1_out1_92),  // double
                       .iz_1_1(IW_1_1_out1)  // double
                       );

  always @* IW_1_1_out1_double = $bitstoreal(IW_1_1_out1);

  // <S2>/b{1}
  initial b_1_out1 = 0.78280396777667183;



  // <S2>/netsum
  always @* netsum_out1 = IW_1_1_out1_double + b_1_out1;



  // <S2>/poslin
  poslin   u_poslin   (.n($realtobits(netsum_out1)),  // double
                       .a(poslin_out1)  // double
                       );

  assign a_1 = poslin_out1;

endmodule  // Layer_1

