// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\Layer_2.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Layer_2
// Source Path: untitled/Pattern Recognition Neural Network/Layer 2
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Layer_2
          (
           a_1,
           a_2
          );


  input   [63:0] a_1;  // double
  output  [63:0] a_2;  // double


  wire [63:0] Delays_1_out1;  // ufix64
  wire [63:0] LW_2_1_out1;  // ufix64
  real LW_2_1_out1_double;  // double
  real b_2_out1;  // double
  real netsum_out1;  // double
  wire [63:0] poslin_out1;  // ufix64


  // <S3>/Delays 1
  Delays_1_block   u_Delays_1   (.p_2(a_1),  // double
                                 .pd_2_1(Delays_1_out1)  // double
                                 );

  // <S3>/LW{2,1}
  LW_2_1   u_LW_2_1   (.ad_2_1(Delays_1_out1),  // double
                       .lz_2_1(LW_2_1_out1)  // double
                       );

  always @* LW_2_1_out1_double = $bitstoreal(LW_2_1_out1);

  // <S3>/b{2}
  initial b_2_out1 = -0.71130264107874652;



  // <S3>/netsum
  always @* netsum_out1 = LW_2_1_out1_double + b_2_out1;



  // <S3>/poslin
  poslin_block   u_poslin   (.n($realtobits(netsum_out1)),  // double
                             .a(poslin_out1)  // double
                             );

  assign a_2 = poslin_out1;

endmodule  // Layer_2

