// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\LW_2_1.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LW_2_1
// Source Path: untitled/Pattern Recognition Neural Network/Layer 2/LW{2,1}
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LW_2_1
          (
           ad_2_1,
           lz_2_1
          );


  input   [63:0] ad_2_1;  // double
  output  [63:0] lz_2_1;  // double


  real IW_2_1_1_out1;  // double
  wire [63:0] dotprod1_out1;  // ufix64


  // <S11>/IW{2,1}(1,:)'
  initial IW_2_1_1_out1 = 0.72835968338909418;



  // <S11>/dotprod1
  // 
  // <S11>/Mux
  dotprod1_block   u_dotprod1   (.In1($realtobits(IW_2_1_1_out1)),  // double
                                 .In2(ad_2_1),  // double
                                 .Out1(dotprod1_out1)  // double
                                 );

  assign lz_2_1 = dotprod1_out1;

endmodule  // LW_2_1

