// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\poslin_block.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: poslin_block
// Source Path: untitled/Pattern Recognition Neural Network/Layer 2/poslin
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module poslin_block
          (
           n,
           a
          );


  input   [63:0] n;  // double
  output  [63:0] a;  // double


  real n_double;  // double
  real Saturation_out1;  // double


  always @* n_double = $bitstoreal(n);

  // <S12>/Saturation
  always @* Saturation_out1 = (n_double < 0.0 ? 0.0 :
              n_double);



  assign a = $realtobits(Saturation_out1);

endmodule  // poslin_block

