// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\Process_Output_1.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Process_Output_1
// Source Path: untitled/Pattern Recognition Neural Network/Process Output 1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Process_Output_1
          (
           a,
           y
          );


  input   [63:0] a;  // double
  output  [63:0] y;  // double




  assign y = a;

endmodule  // Process_Output_1

