// -------------------------------------------------------------
// 
// File Name: F:\Users\user\Downloads\fyp_upm-2\fyp_upm\codes_cacamerba\FYP\work\simulink_NN_relu\untitled\removeconstantrows.v
// Created: 2020-08-17 20:06:13
// 
// Generated by MATLAB 9.0 and HDL Coder 3.8
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: removeconstantrows
// Source Path: untitled/Pattern Recognition Neural Network/Process Input 1/removeconstantrows
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module removeconstantrows
          (
           x_0,
           x_1,
           x_2,
           x_3,
           x_4,
           x_5,
           x_6,
           x_7,
           x_8,
           x_9,
           x_10,
           x_11,
           x_12,
           x_13,
           x_14,
           x_15,
           x_16,
           x_17,
           x_18,
           x_19,
           x_20,
           x_21,
           x_22,
           x_23,
           x_24,
           x_25,
           x_26,
           x_27,
           x_28,
           x_29,
           x_30,
           x_31,
           x_32,
           x_33,
           x_34,
           x_35,
           x_36,
           x_37,
           x_38,
           x_39,
           x_40,
           x_41,
           x_42,
           x_43,
           x_44,
           x_45,
           x_46,
           x_47,
           x_48,
           x_49,
           x_50,
           x_51,
           x_52,
           x_53,
           x_54,
           x_55,
           x_56,
           x_57,
           x_58,
           x_59,
           x_60,
           x_61,
           x_62,
           x_63,
           x_64,
           x_65,
           x_66,
           x_67,
           x_68,
           x_69,
           x_70,
           x_71,
           x_72,
           x_73,
           x_74,
           x_75,
           x_76,
           x_77,
           x_78,
           x_79,
           x_80,
           x_81,
           x_82,
           x_83,
           x_84,
           x_85,
           x_86,
           x_87,
           x_88,
           x_89,
           x_90,
           x_91,
           x_92,
           x_93,
           x_94,
           x_95,
           x_96,
           x_97,
           x_98,
           x_99,
           x_100,
           x_101,
           x_102,
           x_103,
           x_104,
           x_105,
           x_106,
           x_107,
           x_108,
           x_109,
           x_110,
           x_111,
           x_112,
           x_113,
           x_114,
           x_115,
           x_116,
           x_117,
           y_0,
           y_1,
           y_2,
           y_3,
           y_4,
           y_5,
           y_6,
           y_7,
           y_8,
           y_9,
           y_10,
           y_11,
           y_12,
           y_13,
           y_14,
           y_15,
           y_16,
           y_17,
           y_18,
           y_19,
           y_20,
           y_21,
           y_22,
           y_23,
           y_24,
           y_25,
           y_26,
           y_27,
           y_28,
           y_29,
           y_30,
           y_31,
           y_32,
           y_33,
           y_34,
           y_35,
           y_36,
           y_37,
           y_38,
           y_39,
           y_40,
           y_41,
           y_42,
           y_43,
           y_44,
           y_45,
           y_46,
           y_47,
           y_48,
           y_49,
           y_50,
           y_51,
           y_52,
           y_53,
           y_54,
           y_55,
           y_56,
           y_57,
           y_58,
           y_59,
           y_60,
           y_61,
           y_62,
           y_63,
           y_64,
           y_65,
           y_66,
           y_67,
           y_68,
           y_69,
           y_70,
           y_71,
           y_72,
           y_73,
           y_74,
           y_75,
           y_76,
           y_77,
           y_78,
           y_79,
           y_80,
           y_81,
           y_82,
           y_83,
           y_84,
           y_85,
           y_86,
           y_87,
           y_88,
           y_89,
           y_90,
           y_91,
           y_92
          );


  input   [63:0] x_0;  // double
  input   [63:0] x_1;  // double
  input   [63:0] x_2;  // double
  input   [63:0] x_3;  // double
  input   [63:0] x_4;  // double
  input   [63:0] x_5;  // double
  input   [63:0] x_6;  // double
  input   [63:0] x_7;  // double
  input   [63:0] x_8;  // double
  input   [63:0] x_9;  // double
  input   [63:0] x_10;  // double
  input   [63:0] x_11;  // double
  input   [63:0] x_12;  // double
  input   [63:0] x_13;  // double
  input   [63:0] x_14;  // double
  input   [63:0] x_15;  // double
  input   [63:0] x_16;  // double
  input   [63:0] x_17;  // double
  input   [63:0] x_18;  // double
  input   [63:0] x_19;  // double
  input   [63:0] x_20;  // double
  input   [63:0] x_21;  // double
  input   [63:0] x_22;  // double
  input   [63:0] x_23;  // double
  input   [63:0] x_24;  // double
  input   [63:0] x_25;  // double
  input   [63:0] x_26;  // double
  input   [63:0] x_27;  // double
  input   [63:0] x_28;  // double
  input   [63:0] x_29;  // double
  input   [63:0] x_30;  // double
  input   [63:0] x_31;  // double
  input   [63:0] x_32;  // double
  input   [63:0] x_33;  // double
  input   [63:0] x_34;  // double
  input   [63:0] x_35;  // double
  input   [63:0] x_36;  // double
  input   [63:0] x_37;  // double
  input   [63:0] x_38;  // double
  input   [63:0] x_39;  // double
  input   [63:0] x_40;  // double
  input   [63:0] x_41;  // double
  input   [63:0] x_42;  // double
  input   [63:0] x_43;  // double
  input   [63:0] x_44;  // double
  input   [63:0] x_45;  // double
  input   [63:0] x_46;  // double
  input   [63:0] x_47;  // double
  input   [63:0] x_48;  // double
  input   [63:0] x_49;  // double
  input   [63:0] x_50;  // double
  input   [63:0] x_51;  // double
  input   [63:0] x_52;  // double
  input   [63:0] x_53;  // double
  input   [63:0] x_54;  // double
  input   [63:0] x_55;  // double
  input   [63:0] x_56;  // double
  input   [63:0] x_57;  // double
  input   [63:0] x_58;  // double
  input   [63:0] x_59;  // double
  input   [63:0] x_60;  // double
  input   [63:0] x_61;  // double
  input   [63:0] x_62;  // double
  input   [63:0] x_63;  // double
  input   [63:0] x_64;  // double
  input   [63:0] x_65;  // double
  input   [63:0] x_66;  // double
  input   [63:0] x_67;  // double
  input   [63:0] x_68;  // double
  input   [63:0] x_69;  // double
  input   [63:0] x_70;  // double
  input   [63:0] x_71;  // double
  input   [63:0] x_72;  // double
  input   [63:0] x_73;  // double
  input   [63:0] x_74;  // double
  input   [63:0] x_75;  // double
  input   [63:0] x_76;  // double
  input   [63:0] x_77;  // double
  input   [63:0] x_78;  // double
  input   [63:0] x_79;  // double
  input   [63:0] x_80;  // double
  input   [63:0] x_81;  // double
  input   [63:0] x_82;  // double
  input   [63:0] x_83;  // double
  input   [63:0] x_84;  // double
  input   [63:0] x_85;  // double
  input   [63:0] x_86;  // double
  input   [63:0] x_87;  // double
  input   [63:0] x_88;  // double
  input   [63:0] x_89;  // double
  input   [63:0] x_90;  // double
  input   [63:0] x_91;  // double
  input   [63:0] x_92;  // double
  input   [63:0] x_93;  // double
  input   [63:0] x_94;  // double
  input   [63:0] x_95;  // double
  input   [63:0] x_96;  // double
  input   [63:0] x_97;  // double
  input   [63:0] x_98;  // double
  input   [63:0] x_99;  // double
  input   [63:0] x_100;  // double
  input   [63:0] x_101;  // double
  input   [63:0] x_102;  // double
  input   [63:0] x_103;  // double
  input   [63:0] x_104;  // double
  input   [63:0] x_105;  // double
  input   [63:0] x_106;  // double
  input   [63:0] x_107;  // double
  input   [63:0] x_108;  // double
  input   [63:0] x_109;  // double
  input   [63:0] x_110;  // double
  input   [63:0] x_111;  // double
  input   [63:0] x_112;  // double
  input   [63:0] x_113;  // double
  input   [63:0] x_114;  // double
  input   [63:0] x_115;  // double
  input   [63:0] x_116;  // double
  input   [63:0] x_117;  // double
  output  [63:0] y_0;  // double
  output  [63:0] y_1;  // double
  output  [63:0] y_2;  // double
  output  [63:0] y_3;  // double
  output  [63:0] y_4;  // double
  output  [63:0] y_5;  // double
  output  [63:0] y_6;  // double
  output  [63:0] y_7;  // double
  output  [63:0] y_8;  // double
  output  [63:0] y_9;  // double
  output  [63:0] y_10;  // double
  output  [63:0] y_11;  // double
  output  [63:0] y_12;  // double
  output  [63:0] y_13;  // double
  output  [63:0] y_14;  // double
  output  [63:0] y_15;  // double
  output  [63:0] y_16;  // double
  output  [63:0] y_17;  // double
  output  [63:0] y_18;  // double
  output  [63:0] y_19;  // double
  output  [63:0] y_20;  // double
  output  [63:0] y_21;  // double
  output  [63:0] y_22;  // double
  output  [63:0] y_23;  // double
  output  [63:0] y_24;  // double
  output  [63:0] y_25;  // double
  output  [63:0] y_26;  // double
  output  [63:0] y_27;  // double
  output  [63:0] y_28;  // double
  output  [63:0] y_29;  // double
  output  [63:0] y_30;  // double
  output  [63:0] y_31;  // double
  output  [63:0] y_32;  // double
  output  [63:0] y_33;  // double
  output  [63:0] y_34;  // double
  output  [63:0] y_35;  // double
  output  [63:0] y_36;  // double
  output  [63:0] y_37;  // double
  output  [63:0] y_38;  // double
  output  [63:0] y_39;  // double
  output  [63:0] y_40;  // double
  output  [63:0] y_41;  // double
  output  [63:0] y_42;  // double
  output  [63:0] y_43;  // double
  output  [63:0] y_44;  // double
  output  [63:0] y_45;  // double
  output  [63:0] y_46;  // double
  output  [63:0] y_47;  // double
  output  [63:0] y_48;  // double
  output  [63:0] y_49;  // double
  output  [63:0] y_50;  // double
  output  [63:0] y_51;  // double
  output  [63:0] y_52;  // double
  output  [63:0] y_53;  // double
  output  [63:0] y_54;  // double
  output  [63:0] y_55;  // double
  output  [63:0] y_56;  // double
  output  [63:0] y_57;  // double
  output  [63:0] y_58;  // double
  output  [63:0] y_59;  // double
  output  [63:0] y_60;  // double
  output  [63:0] y_61;  // double
  output  [63:0] y_62;  // double
  output  [63:0] y_63;  // double
  output  [63:0] y_64;  // double
  output  [63:0] y_65;  // double
  output  [63:0] y_66;  // double
  output  [63:0] y_67;  // double
  output  [63:0] y_68;  // double
  output  [63:0] y_69;  // double
  output  [63:0] y_70;  // double
  output  [63:0] y_71;  // double
  output  [63:0] y_72;  // double
  output  [63:0] y_73;  // double
  output  [63:0] y_74;  // double
  output  [63:0] y_75;  // double
  output  [63:0] y_76;  // double
  output  [63:0] y_77;  // double
  output  [63:0] y_78;  // double
  output  [63:0] y_79;  // double
  output  [63:0] y_80;  // double
  output  [63:0] y_81;  // double
  output  [63:0] y_82;  // double
  output  [63:0] y_83;  // double
  output  [63:0] y_84;  // double
  output  [63:0] y_85;  // double
  output  [63:0] y_86;  // double
  output  [63:0] y_87;  // double
  output  [63:0] y_88;  // double
  output  [63:0] y_89;  // double
  output  [63:0] y_90;  // double
  output  [63:0] y_91;  // double
  output  [63:0] y_92;  // double




  assign y_0 = x_7;

  assign y_1 = x_8;

  assign y_2 = x_9;

  assign y_3 = x_10;

  assign y_4 = x_11;

  assign y_5 = x_17;

  assign y_6 = x_18;

  assign y_7 = x_19;

  assign y_8 = x_20;

  assign y_9 = x_21;

  assign y_10 = x_22;

  assign y_11 = x_23;

  assign y_12 = x_24;

  assign y_13 = x_25;

  assign y_14 = x_26;

  assign y_15 = x_27;

  assign y_16 = x_28;

  assign y_17 = x_29;

  assign y_18 = x_30;

  assign y_19 = x_31;

  assign y_20 = x_32;

  assign y_21 = x_33;

  assign y_22 = x_34;

  assign y_23 = x_35;

  assign y_24 = x_36;

  assign y_25 = x_37;

  assign y_26 = x_38;

  assign y_27 = x_39;

  assign y_28 = x_40;

  assign y_29 = x_41;

  assign y_30 = x_42;

  assign y_31 = x_43;

  assign y_32 = x_44;

  assign y_33 = x_45;

  assign y_34 = x_46;

  assign y_35 = x_47;

  assign y_36 = x_48;

  assign y_37 = x_49;

  assign y_38 = x_50;

  assign y_39 = x_51;

  assign y_40 = x_52;

  assign y_41 = x_53;

  assign y_42 = x_54;

  assign y_43 = x_55;

  assign y_44 = x_56;

  assign y_45 = x_57;

  assign y_46 = x_58;

  assign y_47 = x_59;

  assign y_48 = x_60;

  assign y_49 = x_61;

  assign y_50 = x_62;

  assign y_51 = x_63;

  assign y_52 = x_64;

  assign y_53 = x_65;

  assign y_54 = x_66;

  assign y_55 = x_67;

  assign y_56 = x_68;

  assign y_57 = x_69;

  assign y_58 = x_70;

  assign y_59 = x_71;

  assign y_60 = x_72;

  assign y_61 = x_73;

  assign y_62 = x_74;

  assign y_63 = x_75;

  assign y_64 = x_76;

  assign y_65 = x_77;

  assign y_66 = x_78;

  assign y_67 = x_79;

  assign y_68 = x_80;

  assign y_69 = x_81;

  assign y_70 = x_82;

  assign y_71 = x_83;

  assign y_72 = x_84;

  assign y_73 = x_85;

  assign y_74 = x_86;

  assign y_75 = x_87;

  assign y_76 = x_88;

  assign y_77 = x_89;

  assign y_78 = x_90;

  assign y_79 = x_91;

  assign y_80 = x_92;

  assign y_81 = x_93;

  assign y_82 = x_94;

  assign y_83 = x_95;

  assign y_84 = x_96;

  assign y_85 = x_97;

  assign y_86 = x_98;

  assign y_87 = x_99;

  assign y_88 = x_100;

  assign y_89 = x_101;

  assign y_90 = x_102;

  assign y_91 = x_103;

  assign y_92 = x_104;

endmodule  // removeconstantrows

